name: Update TwitchAdBlock

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main

      - name: Download TwitchAdBlock IPA
        run: |
          JSON=$(curl -s "https://api.github.com/repos/level3tjg/TwitchAdBlock/releases/latest")
          URL=$(echo "$JSON" | jq -r '.assets[] | select(.name | test("^TwitchAdBlock_[0-9.-]+\\.ipa$")) | .browser_download_url')
          curl -L -o ./TwitchAdBlock.ipa "$URL"

      - name: Release TwitchAdBlock
        uses: ncipollo/release-action@main
        with:
          tag: TwitchAdBlock
          name: TwitchAdBlock
          body: "Latest release of TwitchAdBlock"
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          artifacts: "./TwitchAdBlock.ipa"
          allowUpdates: true
          removeArtifacts: true
